// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "d10f161847b82b9849f04964022c121d"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"53174faa27c3a8feb48325627c9c2697": "1f8b08000000000000ffb493416fda3014c7effe144fe999d40e8484491c2005a9dddaa9a5aceb1042c676828b63478e41b04f3f39298c6d975ee69cde8bdffffddfcfb6934e09184230b692170298d1b92c76963a6934e4528900a1ad384e65bb2d4068c18476c22e1180a66593a5a539060880726e6b18c2020100041be7aafad3f5b5ad5848f5d686cc94d79551c7c2e8d5a9c6ebb00d95faf6068690628c2304504a9d792bb6f47a04ae7ca67567cb1a0114b4fe224be960085dec175cf91c34c9f6ff548827eabc41127acdd67766b4b394f9c2001fc6a3fea4cbf251cef17a9af644cc7b934137ee639a08cafa2c65f120c2240f4e6387527371582220b8fd8611428b85e085a897974c6a511925e947b108b7599d4ae00a6cc560636af70f2042481c1342fe13233fc79f84b2284ec783a8cfe2413c1d902c2591e051d48b70324afbb817c538cfb2691c9c28bc135aa233a11e420b67f4841762894e7c9cd101ba2473e6e28cde39a9ea864ba1cc9aaab0bd97e15bedab96e882c77b13f4b7f3c9e3c8bcbc3e17ecee3e99653fcbbbbdc6f337c9f2e2c7d33efff699262f8f33d3e5b3f93af99e3ce90035bebd64f76c3774662b74ed8f20c007fcb14582b6ff18dfda8ec6ab79c78d5f6976e83f4c38b59deefd51e5d5eb7432e8189a240f5fb7e9cd6af7e24f7d3ebb794668a14ce13b2ab117ca4b499d1b7f8fb8b43e54a6a87de85fe789e6ba79bea13245d0d487a5e13b25bc0cadaa4b9175cd2e43b36d663ec72575f2f7865f010000ffffd67364b11f040000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("../../config", "../../config")
		b.SetResolver("bridge.toml", packr.Pointer{ForwardBox: gk, ForwardPath: "53174faa27c3a8feb48325627c9c2697"})
	}()
	return nil
}()
