// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "d10f161847b82b9849f04964022c121d"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"53174faa27c3a8feb48325627c9c2697": "1f8b08000000000000ffb453516fda3c147df7afb84a9f499d4048f8241e2005a9fdd64e2d655d871032b6635c1c3bb24d05fbf59383a8b2eda52f334ff772cfb9e79cd85e7ac5610cd1d44a263850a32b290e967869345452f108a13d3fcde5792c426845b9f6dcae11802675db25b53945088030661d8c61850000a29df78dfbeffada3634267a6f636aeaebc6a893307a73c1041eba2352dfdec0180a8c710a08a096ba0c5a6c1d0813b80a9db33c5b3b042088fb226be9c3bf190e07ae4213daee7960cef913f1416212a7614fabbc34da5b420332c2c7e96438ebd36a5231bc9d17039eb1c16cd4cf8698e49cd0212d68364a715205e72bce0477ebae75c71ba324f9ac7bee779b0b04aec0361476c6f9bf72489224cb9224f957490423bfe750a659311da5439a8db2f928298b24e52c4d0729ce27c5100fd20c576539cf2284d0ca1b3d6382afd125066f7484ba017cd8f7461fbc54aeb52f94d912159f6f59fce6026a8d3ab6f1f987fed4377b9c9897d76741efeef345f9b3be7bd778f92669257e3cbd57dffe27f9cbe3c2f4d962b9cdbfe74f3a4252337e8431a41f6a636ff65cbb1074848ff8732789ceeba7f8d6f634de2c7b7efa4acae3f061c688edf5ef4faa6a5ee7b351cf903c7ff8ba2f6e368797f06d978b9b678456ca88b051f177ae0295d49509b785491b4a65840b65786a9730b7ed5b8c9511518b8f6bc30e8a071ad2345d92ada3ddd2ec5bcb1f754dbcec0cfc0a0000ffff4dc91e0fed030000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("../../config", "../../config")
		b.SetResolver("bridge.toml", packr.Pointer{ForwardBox: gk, ForwardPath: "53174faa27c3a8feb48325627c9c2697"})
	}()
	return nil
}()
