# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  push:
    branches:
      - smart-bridge

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest,macos-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: make build
        
      - uses: actions/upload-artifact@v2
        with:
          name: foo-${{ matrix.os }}
          path: bin/*
